-- ==============================================================================
-- TABELINK - FINAL POSTGRESQL SCHEMA
-- ==============================================================================
-- Notes:
-- - Guest is not stored in DB. Guest means unauthenticated visitor.
-- - Customer actions reference CUSTOMER_PROFILE.
-- - Owner actions reference OWNER_PROFILE.
-- - Admin actions reference USER_ACCOUNT; the application should enforce Role = 'Admin'.
-- - Cross-table business rules are enforced where practical with composite foreign keys.

-- ==============================================================================
-- 1. BASE ACCOUNTS AND MASTER DATA
-- ==============================================================================

CREATE TABLE USER_ACCOUNT (
    AccountID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL CHECK (Role IN ('Admin', 'User', 'Owner')),
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending'
        CHECK (Status IN ('Active', 'Banned', 'Pending', 'Disabled')),
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (BTRIM(Email) <> '')
);

CREATE UNIQUE INDEX ux_user_account_email_lower
    ON USER_ACCOUNT (LOWER(Email));

CREATE INDEX idx_user_account_role ON USER_ACCOUNT(Role);
CREATE INDEX idx_user_account_status ON USER_ACCOUNT(Status);

CREATE TABLE FEATURE_MASTER (
    FeatureID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FeatureCode VARCHAR(100) UNIQUE NOT NULL,
    FeatureNameVN VARCHAR(255) NOT NULL,
    FeatureNameJP VARCHAR(255) NOT NULL
);

CREATE TABLE PAYMENT_METHOD (
    PaymentMethodID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MethodCode VARCHAR(100) UNIQUE NOT NULL,
    MethodName VARCHAR(255) NOT NULL
);

CREATE TABLE HASHTAG (
    TagID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE SPECIAL_REQUEST_TEMPLATE (
    TemplateID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TextVN TEXT NOT NULL,
    TextJP TEXT NOT NULL,
    RequestType VARCHAR(50) NOT NULL
        CHECK (RequestType IN ('Coriander', 'LessSpicy', 'VATInvoice', 'Other'))
);

CREATE TABLE BADGE_MASTER (
    BadgeID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BadgeCode VARCHAR(100) UNIQUE NOT NULL,
    BadgeNameVN VARCHAR(255) NOT NULL,
    BadgeNameJP VARCHAR(255) NOT NULL,
    DescriptionVN TEXT,
    DescriptionJP TEXT,
    Criteria TEXT
);

INSERT INTO BADGE_MASTER (
    BadgeCode,
    BadgeNameVN,
    BadgeNameJP,
    DescriptionVN,
    DescriptionJP,
    Criteria
)
VALUES (
    'VERIFIED',
    'Đã xác thực',
    '認証済み',
    'Nhà hàng đã được TABELINK xác thực sau khi kiểm tra hồ sơ.',
    '提出書類の確認後、TABELINKにより認証された店舗です。',
    'Giấy phép kinh doanh, chứng nhận an toàn thực phẩm'
)
ON CONFLICT (BadgeCode) DO NOTHING;

-- ==============================================================================
-- 2. USER PROFILES AND ACCOUNT-RELATED FEATURES
-- ==============================================================================

CREATE TABLE CUSTOMER_PROFILE (
    AccountID INT PRIMARY KEY
        REFERENCES USER_ACCOUNT(AccountID) ON DELETE CASCADE,
    FullName VARCHAR(255) NOT NULL,
    DisplayName VARCHAR(255),
    Gender VARCHAR(20),
    DOB DATE,
    Nationality VARCHAR(100),
    Purpose VARCHAR(255),
    AvatarURL TEXT
);

CREATE TABLE OWNER_PROFILE (
    AccountID INT PRIMARY KEY
        REFERENCES USER_ACCOUNT(AccountID) ON DELETE CASCADE,
    FullName VARCHAR(255) NOT NULL,
    Phone VARCHAR(50),
    BusinessName VARCHAR(255),
    AvatarURL TEXT
);


CREATE TABLE USER_FOLLOW (
    FollowerAccountID INT NOT NULL
        REFERENCES CUSTOMER_PROFILE(AccountID) ON DELETE CASCADE,
    FollowedAccountID INT NOT NULL
        REFERENCES CUSTOMER_PROFILE(AccountID) ON DELETE CASCADE,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FollowerAccountID, FollowedAccountID),
    CHECK (FollowerAccountID <> FollowedAccountID)
);

CREATE TABLE MODERATION_LOG (
    LogID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AdminAccountID INT NOT NULL
        REFERENCES USER_ACCOUNT(AccountID),
    TargetType VARCHAR(50) NOT NULL
        CHECK (TargetType IN ('Review', 'Promotion', 'BadgeApplication', 'Account', 'RestaurantMedia')),
    TargetID INT NOT NULL,
    ActionType VARCHAR(50) NOT NULL
        CHECK (ActionType IN ('Approve', 'Reject', 'Hide', 'Delete', 'Ban', 'Unban')),
    Reason TEXT,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_moderation_log_admin ON MODERATION_LOG(AdminAccountID);
CREATE INDEX idx_moderation_log_target ON MODERATION_LOG(TargetType, TargetID);

-- ==============================================================================
-- 3. RESTAURANT AND MENU MANAGEMENT
-- ==============================================================================

CREATE TABLE RESTAURANT (
    RestaurantID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OwnerAccountID INT NOT NULL
        REFERENCES OWNER_PROFILE(AccountID) ON DELETE CASCADE,
    NameVN VARCHAR(255) NOT NULL,
    NameJP VARCHAR(255) NOT NULL,
    Address TEXT NOT NULL,
    Latitude DECIMAL(10, 8),
    Longitude DECIMAL(11, 8),
    DescriptionVN TEXT,
    DescriptionJP TEXT,
    IssuesVAT BOOLEAN NOT NULL DEFAULT FALSE,
    Phone VARCHAR(50),
    OpeningHours VARCHAR(255),
    Status VARCHAR(50) NOT NULL DEFAULT 'Draft'
        CHECK (Status IN ('Draft', 'PendingApproval', 'Active', 'Suspended')),
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (Latitude BETWEEN -90 AND 90),
    CHECK (Longitude BETWEEN -180 AND 180),
    UNIQUE (RestaurantID, OwnerAccountID)
);

CREATE INDEX idx_restaurant_owner ON RESTAURANT(OwnerAccountID);
CREATE INDEX idx_restaurant_status ON RESTAURANT(Status);
CREATE INDEX idx_restaurant_location ON RESTAURANT(Latitude, Longitude);

CREATE TABLE RESTAURANT_MEDIA (
    MediaID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    MediaURL TEXT NOT NULL,
    MediaType VARCHAR(50) NOT NULL
        CHECK (MediaType IN ('Photo', 'Cover', 'Other')),
    SortOrder INT NOT NULL DEFAULT 0,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending'
        CHECK (Status IN ('Pending', 'Approved', 'Rejected'))
);

CREATE INDEX idx_restaurant_media_restaurant ON RESTAURANT_MEDIA(RestaurantID);

CREATE TABLE RESTAURANT_FEATURE (
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    FeatureID INT NOT NULL
        REFERENCES FEATURE_MASTER(FeatureID) ON DELETE CASCADE,
    PRIMARY KEY (RestaurantID, FeatureID)
);

CREATE INDEX idx_restaurant_feature_feature ON RESTAURANT_FEATURE(FeatureID);

CREATE TABLE RESTAURANT_PAYMENT_METHOD (
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    PaymentMethodID INT NOT NULL
        REFERENCES PAYMENT_METHOD(PaymentMethodID) ON DELETE CASCADE,
    PRIMARY KEY (RestaurantID, PaymentMethodID)
);

CREATE INDEX idx_restaurant_payment_method_method
    ON RESTAURANT_PAYMENT_METHOD(PaymentMethodID);

CREATE TABLE MENU_ITEM (
    ItemID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    NameVN VARCHAR(255) NOT NULL,
    NameJP VARCHAR(255) NOT NULL,
    Price DECIMAL(12, 2) NOT NULL CHECK (Price >= 0),
    DescriptionVN TEXT,
    DescriptionJP TEXT,
    Ingredients TEXT,
    IsRecommendedForJP BOOLEAN NOT NULL DEFAULT FALSE,
    ImageURL TEXT,
    ImagePublicID TEXT,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    DeletedAt TIMESTAMPTZ,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ItemID, RestaurantID)
);

CREATE INDEX idx_menu_item_restaurant ON MENU_ITEM(RestaurantID);
CREATE INDEX idx_menu_item_isactive ON MENU_ITEM(IsActive);
CREATE INDEX idx_menu_item_deleted_at ON MENU_ITEM(DeletedAt);

CREATE TABLE MENU_ITEM_CRITERION (
    CriterionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ItemID INT NOT NULL
        REFERENCES MENU_ITEM(ItemID) ON DELETE CASCADE,
    CriterionName VARCHAR(255) NOT NULL,
    RatingLevel INT NOT NULL CHECK (RatingLevel BETWEEN 1 AND 5),
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (CriterionName = BTRIM(CriterionName)),
    CHECK (CriterionName <> ''),
    CHECK (CriterionName !~ '[\r\n]')
);

CREATE INDEX idx_menu_item_criterion_item
    ON MENU_ITEM_CRITERION(ItemID);

CREATE TABLE RESTAURANT_TABLE (
    TableID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    TableName VARCHAR(100) NOT NULL,
    Capacity INT NOT NULL CHECK (Capacity > 0),
    Status VARCHAR(50) NOT NULL DEFAULT 'Empty'
        CHECK (Status IN ('Empty', 'Using', 'Reserved')),
    PositionX DECIMAL(8, 2),
    PositionY DECIMAL(8, 2),
    Width DECIMAL(8, 2) CHECK (Width > 0),
    Height DECIMAL(8, 2) CHECK (Height > 0),
    Zone VARCHAR(100),
    UNIQUE (RestaurantID, TableName),
    UNIQUE (TableID, RestaurantID)
);

CREATE INDEX idx_restaurant_table_restaurant ON RESTAURANT_TABLE(RestaurantID);

-- ==============================================================================
-- 4. RESERVATION AND ORDERING
-- ==============================================================================

CREATE TABLE RESERVATION (
    ReservationID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerAccountID INT NOT NULL
        REFERENCES CUSTOMER_PROFILE(AccountID),
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID),
    TableID INT,
    ReservationDateTime TIMESTAMPTZ NOT NULL,
    Pax INT NOT NULL CHECK (Pax > 0),
    Note TEXT,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending'
        CHECK (Status IN ('Pending', 'Confirmed', 'Arrived', 'Completed', 'Cancelled')),
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TableID, RestaurantID)
        REFERENCES RESTAURANT_TABLE(TableID, RestaurantID)
        ON DELETE RESTRICT,
    UNIQUE (ReservationID, RestaurantID),
    UNIQUE (ReservationID, CustomerAccountID)
);

CREATE INDEX idx_reservation_customer ON RESERVATION(CustomerAccountID);
CREATE INDEX idx_reservation_restaurant ON RESERVATION(RestaurantID);
CREATE INDEX idx_reservation_date ON RESERVATION(ReservationDateTime);
CREATE INDEX idx_reservation_status ON RESERVATION(Status);
CREATE UNIQUE INDEX ux_reservation_table_timeslot_active
    ON RESERVATION(RestaurantID, TableID, ReservationDateTime)
    WHERE TableID IS NOT NULL AND Status IN ('Pending', 'Confirmed', 'Arrived');

CREATE TABLE RESERVATION_ITEM (
    ReservationItemID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReservationID INT NOT NULL,
    RestaurantID INT NOT NULL,
    ItemID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(12, 2) NOT NULL CHECK (UnitPrice >= 0),
    Note TEXT,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ReservationID, RestaurantID)
        REFERENCES RESERVATION(ReservationID, RestaurantID)
        ON DELETE CASCADE,
    FOREIGN KEY (ItemID, RestaurantID)
        REFERENCES MENU_ITEM(ItemID, RestaurantID),
    UNIQUE (ReservationID, ItemID)
);

CREATE INDEX idx_reservation_item_reservation ON RESERVATION_ITEM(ReservationID);
CREATE INDEX idx_reservation_item_item ON RESERVATION_ITEM(ItemID);

CREATE TABLE RESERVATION_SPECIAL_REQUEST (
    RequestID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReservationID INT NOT NULL
        REFERENCES RESERVATION(ReservationID) ON DELETE CASCADE,
    TemplateID INT
        REFERENCES SPECIAL_REQUEST_TEMPLATE(TemplateID) ON DELETE SET NULL,
    CustomText TEXT,
    CHECK (TemplateID IS NOT NULL OR NULLIF(BTRIM(CustomText), '') IS NOT NULL)
);

CREATE INDEX idx_reservation_special_request_reservation
    ON RESERVATION_SPECIAL_REQUEST(ReservationID);

-- ==============================================================================
-- 5. REVIEW AND SOCIAL FEATURES
-- ==============================================================================

CREATE TABLE REVIEW (
    ReviewID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerAccountID INT NOT NULL
        REFERENCES CUSTOMER_PROFILE(AccountID) ON DELETE CASCADE,
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    ReservationID INT UNIQUE,
    Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    ToiletCleanliness INT CHECK (ToiletCleanliness BETWEEN 1 AND 5),
    DishCleanliness INT CHECK (DishCleanliness BETWEEN 1 AND 5),
    SpaceCleanliness INT CHECK (SpaceCleanliness BETWEEN 1 AND 5),
    Content TEXT,
    Sentiment VARCHAR(50)
        CHECK (Sentiment IN ('Positive', 'Neutral', 'Negative')),
    IsJapaneseTag BOOLEAN NOT NULL DEFAULT FALSE,
    Status VARCHAR(50) NOT NULL DEFAULT 'Visible'
        CHECK (Status IN ('Visible', 'Hidden', 'Deleted')),
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ReservationID, RestaurantID)
        REFERENCES RESERVATION(ReservationID, RestaurantID),
    FOREIGN KEY (ReservationID, CustomerAccountID)
        REFERENCES RESERVATION(ReservationID, CustomerAccountID)
);

CREATE INDEX idx_review_restaurant ON REVIEW(RestaurantID);
CREATE INDEX idx_review_customer ON REVIEW(CustomerAccountID);
CREATE INDEX idx_review_status ON REVIEW(Status);
CREATE INDEX idx_review_sentiment ON REVIEW(Sentiment);

CREATE TABLE REVIEW_MEDIA (
    MediaID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReviewID INT NOT NULL
        REFERENCES REVIEW(ReviewID) ON DELETE CASCADE,
    MediaURL TEXT NOT NULL,
    MediaType VARCHAR(50) NOT NULL CHECK (MediaType IN ('Photo', 'Video')),
    SortOrder INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_review_media_review ON REVIEW_MEDIA(ReviewID);

CREATE TABLE REVIEW_TAG (
    ReviewID INT NOT NULL
        REFERENCES REVIEW(ReviewID) ON DELETE CASCADE,
    TagID INT NOT NULL
        REFERENCES HASHTAG(TagID) ON DELETE CASCADE,
    PRIMARY KEY (ReviewID, TagID)
);

CREATE INDEX idx_review_tag_tag ON REVIEW_TAG(TagID);

-- ==============================================================================
-- 6. PROMOTION, BADGE, AND ANALYTICS
-- ==============================================================================

CREATE TABLE PROMOTION (
    PromotionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RestaurantID INT NOT NULL,
    CreatedByOwnerAccountID INT NOT NULL,
    ApprovedByAdminID INT
        REFERENCES USER_ACCOUNT(AccountID),
    PromotionType VARCHAR(50) NOT NULL
        CHECK (PromotionType IN ('Campaign', 'Advertisement')),
    TargetAudience VARCHAR(255),
    TitleVN VARCHAR(255) NOT NULL,
    TitleJP VARCHAR(255) NOT NULL,
    ContentVN TEXT,
    ContentJP TEXT,
    MediaURL TEXT,
    TermsVN TEXT,
    TermsJP TEXT,
    StartDate TIMESTAMPTZ NOT NULL,
    EndDate TIMESTAMPTZ NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending'
        CHECK (Status IN ('Pending', 'Active', 'Rejected', 'Ended')),
    Impressions INT NOT NULL DEFAULT 0 CHECK (Impressions >= 0),
    Clicks INT NOT NULL DEFAULT 0 CHECK (Clicks >= 0),
    TotalCost DECIMAL(12, 2) NOT NULL DEFAULT 0 CHECK (TotalCost >= 0),
    FOREIGN KEY (CreatedByOwnerAccountID)
        REFERENCES OWNER_PROFILE(AccountID),
    FOREIGN KEY (RestaurantID, CreatedByOwnerAccountID)
        REFERENCES RESTAURANT(RestaurantID, OwnerAccountID)
        ON DELETE CASCADE,
    CHECK (EndDate > StartDate),
    CHECK (Clicks <= Impressions),
    CHECK (Status NOT IN ('Active', 'Rejected', 'Ended') OR ApprovedByAdminID IS NOT NULL),
    UNIQUE (PromotionID, RestaurantID)
);

CREATE INDEX idx_promotion_restaurant ON PROMOTION(RestaurantID);
CREATE INDEX idx_promotion_owner ON PROMOTION(CreatedByOwnerAccountID);
CREATE INDEX idx_promotion_status_date ON PROMOTION(Status, StartDate, EndDate);

CREATE TABLE PROMOTION_REDEMPTION (
    RedemptionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PromotionID INT NOT NULL,
    RestaurantID INT NOT NULL,
    ReservationID INT NOT NULL,
    CustomerAccountID INT NOT NULL,
    RedemptionStatus VARCHAR(50) NOT NULL DEFAULT 'Redeemed'
        CHECK (RedemptionStatus IN ('Redeemed', 'Cancelled')),
    RedeemedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PromotionID, RestaurantID)
        REFERENCES PROMOTION(PromotionID, RestaurantID)
        ON DELETE CASCADE,
    FOREIGN KEY (ReservationID, RestaurantID)
        REFERENCES RESERVATION(ReservationID, RestaurantID)
        ON DELETE CASCADE,
    FOREIGN KEY (ReservationID, CustomerAccountID)
        REFERENCES RESERVATION(ReservationID, CustomerAccountID)
        ON DELETE CASCADE,
    FOREIGN KEY (CustomerAccountID)
        REFERENCES CUSTOMER_PROFILE(AccountID)
        ON DELETE CASCADE,
    UNIQUE (PromotionID, ReservationID)
);

CREATE INDEX idx_promotion_redemption_promotion
    ON PROMOTION_REDEMPTION(PromotionID);
CREATE INDEX idx_promotion_redemption_restaurant_date
    ON PROMOTION_REDEMPTION(RestaurantID, RedeemedAt);
CREATE INDEX idx_promotion_redemption_reservation
    ON PROMOTION_REDEMPTION(ReservationID);

CREATE TABLE BADGE_APPLICATION (
    AppID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RestaurantID INT NOT NULL,
    BadgeID INT NOT NULL
        REFERENCES BADGE_MASTER(BadgeID),
    SubmittedByOwnerAccountID INT NOT NULL,
    ReviewedByAdminID INT
        REFERENCES USER_ACCOUNT(AccountID),
    BusinessLicenseURL TEXT,
    BusinessLicensePublicID TEXT,
    FoodSafetyCertURL TEXT,
    FoodSafetyCertPublicID TEXT,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending'
        CHECK (Status IN ('Pending', 'Approved', 'Rejected')),
    SubmittedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ReviewedAt TIMESTAMPTZ,
    ReviewNote TEXT,
    FOREIGN KEY (SubmittedByOwnerAccountID)
        REFERENCES OWNER_PROFILE(AccountID),
    FOREIGN KEY (RestaurantID, SubmittedByOwnerAccountID)
        REFERENCES RESTAURANT(RestaurantID, OwnerAccountID)
        ON DELETE CASCADE,
    CHECK (
        Status = 'Pending'
        OR (ReviewedByAdminID IS NOT NULL AND ReviewedAt IS NOT NULL)
    )
);

CREATE INDEX idx_badge_application_restaurant ON BADGE_APPLICATION(RestaurantID);
CREATE INDEX idx_badge_application_owner ON BADGE_APPLICATION(SubmittedByOwnerAccountID);
CREATE INDEX idx_badge_application_status ON BADGE_APPLICATION(Status);

CREATE TABLE RESTAURANT_BADGE (
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    BadgeID INT NOT NULL
        REFERENCES BADGE_MASTER(BadgeID) ON DELETE CASCADE,
    GrantedByAdminID INT NOT NULL
        REFERENCES USER_ACCOUNT(AccountID),
    GrantedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMPTZ,
    PRIMARY KEY (RestaurantID, BadgeID),
    CHECK (ExpiresAt IS NULL OR ExpiresAt > GrantedAt)
);

CREATE INDEX idx_restaurant_badge_badge ON RESTAURANT_BADGE(BadgeID);

CREATE TABLE RESTAURANT_ANALYTICS_DAILY (
    AnalyticsID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RestaurantID INT NOT NULL
        REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    StatDate DATE NOT NULL,
    VisitCount INT NOT NULL DEFAULT 0 CHECK (VisitCount >= 0),
    JapaneseVisitCount INT NOT NULL DEFAULT 0 CHECK (JapaneseVisitCount >= 0),
    ReviewCount INT NOT NULL DEFAULT 0 CHECK (ReviewCount >= 0),
    ReservationCount INT NOT NULL DEFAULT 0 CHECK (ReservationCount >= 0),
    PeakHour INT CHECK (PeakHour BETWEEN 0 AND 23),
    UNIQUE (RestaurantID, StatDate),
    CHECK (JapaneseVisitCount <= VisitCount)
);

CREATE INDEX idx_restaurant_analytics_date ON RESTAURANT_ANALYTICS_DAILY(StatDate);

CREATE TABLE MENU_ITEM_ANALYTICS_DAILY (
    AnalyticsID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ItemID INT NOT NULL
        REFERENCES MENU_ITEM(ItemID) ON DELETE CASCADE,
    StatDate DATE NOT NULL,
    ViewCount INT NOT NULL DEFAULT 0 CHECK (ViewCount >= 0),
    OrderCount INT NOT NULL DEFAULT 0 CHECK (OrderCount >= 0),
    UNIQUE (ItemID, StatDate)
);

CREATE INDEX idx_menu_analytics_date ON MENU_ITEM_ANALYTICS_DAILY(StatDate);

-- ==============================================================================
-- 7. OPTIONAL UPDATEDAT TRIGGER
-- ==============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UpdatedAt = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_user_account_updated_at
BEFORE UPDATE ON USER_ACCOUNT
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_restaurant_updated_at
BEFORE UPDATE ON RESTAURANT
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_menu_item_updated_at
BEFORE UPDATE ON MENU_ITEM
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_reservation_updated_at
BEFORE UPDATE ON RESERVATION
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_review_updated_at
BEFORE UPDATE ON REVIEW
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
