BEGIN;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'menu_item'
          AND column_name = 'spicylevel'
    ) THEN
        UPDATE menu_item
        SET spicylevel = LEAST(GREATEST(COALESCE(spicylevel, 1), 1), 5)
        WHERE spicylevel IS NULL
           OR spicylevel NOT BETWEEN 1 AND 5;

        ALTER TABLE menu_item
        ALTER COLUMN spicylevel SET DEFAULT 1;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'menu_item'
          AND column_name = 'corianderlevel'
    ) THEN
        UPDATE menu_item
        SET corianderlevel = LEAST(GREATEST(COALESCE(corianderlevel, 1), 1), 5)
        WHERE corianderlevel IS NULL
           OR corianderlevel NOT BETWEEN 1 AND 5;

        ALTER TABLE menu_item
        ALTER COLUMN corianderlevel SET DEFAULT 1;
    END IF;
END;
$$;

ALTER TABLE review
    ADD COLUMN IF NOT EXISTS sentiment VARCHAR(50);

UPDATE review
SET sentiment = CASE
    WHEN rating >= 4 THEN 'Positive'
    WHEN rating = 3 THEN 'Neutral'
    ELSE 'Negative'
END
WHERE sentiment IS NULL;

ALTER TABLE review
    DROP CONSTRAINT IF EXISTS ck_review_sentiment;

ALTER TABLE review
    DROP CONSTRAINT IF EXISTS review_sentiment_check;

ALTER TABLE review
    ADD CONSTRAINT ck_review_sentiment
    CHECK (sentiment IN ('Positive', 'Neutral', 'Negative'));

CREATE INDEX IF NOT EXISTS idx_review_sentiment
    ON review(sentiment);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ux_promotion_id_restaurant'
    ) THEN
        ALTER TABLE promotion
        ADD CONSTRAINT ux_promotion_id_restaurant
        UNIQUE (promotionid, restaurantid);
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS promotion_redemption (
    redemptionid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotionid INT NOT NULL,
    restaurantid INT NOT NULL,
    reservationid INT NOT NULL,
    customeraccountid INT NOT NULL,
    redemptionstatus VARCHAR(50) NOT NULL DEFAULT 'Redeemed'
        CHECK (redemptionstatus IN ('Redeemed', 'Cancelled')),
    redeemedat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (promotionid, restaurantid)
        REFERENCES promotion(promotionid, restaurantid)
        ON DELETE CASCADE,
    FOREIGN KEY (reservationid, restaurantid)
        REFERENCES reservation(reservationid, restaurantid)
        ON DELETE CASCADE,
    FOREIGN KEY (reservationid, customeraccountid)
        REFERENCES reservation(reservationid, customeraccountid)
        ON DELETE CASCADE,
    FOREIGN KEY (customeraccountid)
        REFERENCES customer_profile(accountid)
        ON DELETE CASCADE,
    UNIQUE (promotionid, reservationid)
);

CREATE INDEX IF NOT EXISTS idx_promotion_redemption_promotion
    ON promotion_redemption(promotionid);

CREATE INDEX IF NOT EXISTS idx_promotion_redemption_restaurant_date
    ON promotion_redemption(restaurantid, redeemedat);

CREATE INDEX IF NOT EXISTS idx_promotion_redemption_reservation
    ON promotion_redemption(reservationid);

CREATE INDEX IF NOT EXISTS idx_reservation_table_time
    ON reservation(restaurantid, tableid, reservationdatetime);

COMMIT;
