BEGIN;

CREATE TABLE IF NOT EXISTS restaurant_social_link (
    sociallinkid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurantid INT NOT NULL
        REFERENCES restaurant(restaurantid) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL
        CHECK (provider IN ('Facebook', 'Instagram', 'Website', 'Line', 'Other')),
    url TEXT NOT NULL,
    displaylabel VARCHAR(255),
    sortorder INT NOT NULL DEFAULT 0,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (restaurantid, provider),
    CHECK (BTRIM(url) <> '')
);

CREATE INDEX IF NOT EXISTS idx_restaurant_social_link_restaurant
    ON restaurant_social_link(restaurantid);

CREATE TABLE IF NOT EXISTS menu_category (
    categoryid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurantid INT NOT NULL
        REFERENCES restaurant(restaurantid) ON DELETE CASCADE,
    categorycode VARCHAR(100) NOT NULL,
    categorynamevn VARCHAR(255) NOT NULL,
    categorynamejp VARCHAR(255) NOT NULL,
    sortorder INT NOT NULL DEFAULT 0,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (restaurantid, categorycode),
    UNIQUE (categoryid, restaurantid),
    CHECK (BTRIM(categorycode) <> ''),
    CHECK (BTRIM(categorynamevn) <> ''),
    CHECK (BTRIM(categorynamejp) <> '')
);

CREATE INDEX IF NOT EXISTS idx_menu_category_restaurant
    ON menu_category(restaurantid);

ALTER TABLE menu_item
    ADD COLUMN IF NOT EXISTS categoryid INT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'menu_item_categoryid_restaurantid_fkey'
    ) THEN
        ALTER TABLE menu_item
        ADD CONSTRAINT menu_item_categoryid_restaurantid_fkey
        FOREIGN KEY (categoryid, restaurantid)
        REFERENCES menu_category(categoryid, restaurantid)
        ON DELETE SET NULL (categoryid);
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_menu_item_category
    ON menu_item(categoryid);

COMMIT;
