BEGIN;

CREATE TABLE IF NOT EXISTS blog_post (
    blogid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customeraccountid INT NOT NULL
        REFERENCES customer_profile(accountid) ON DELETE CASCADE,
    restaurantid INT
        REFERENCES restaurant(restaurantid) ON DELETE SET NULL,
    title VARCHAR(255),
    content TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Published'
        CHECK (status IN ('Draft', 'Published', 'Hidden', 'Deleted')),
    createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (BTRIM(content) <> '')
);

CREATE INDEX IF NOT EXISTS idx_blog_post_customer
    ON blog_post(customeraccountid);
CREATE INDEX IF NOT EXISTS idx_blog_post_restaurant
    ON blog_post(restaurantid);
CREATE INDEX IF NOT EXISTS idx_blog_post_status_created
    ON blog_post(status, createdat DESC, blogid DESC);

CREATE TABLE IF NOT EXISTS blog_media (
    mediaid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blogid INT NOT NULL
        REFERENCES blog_post(blogid) ON DELETE CASCADE,
    mediaurl TEXT NOT NULL,
    mediatype VARCHAR(50) NOT NULL CHECK (mediatype IN ('Photo', 'Video')),
    sortorder INT NOT NULL DEFAULT 0,
    CHECK (BTRIM(mediaurl) <> '')
);

CREATE INDEX IF NOT EXISTS idx_blog_media_blog
    ON blog_media(blogid);

CREATE TABLE IF NOT EXISTS blog_tag (
    blogid INT NOT NULL
        REFERENCES blog_post(blogid) ON DELETE CASCADE,
    tagid INT NOT NULL
        REFERENCES hashtag(tagid) ON DELETE CASCADE,
    PRIMARY KEY (blogid, tagid)
);

CREATE INDEX IF NOT EXISTS idx_blog_tag_tag
    ON blog_tag(tagid);

CREATE TABLE IF NOT EXISTS blog_like (
    blogid INT NOT NULL
        REFERENCES blog_post(blogid) ON DELETE CASCADE,
    customeraccountid INT NOT NULL
        REFERENCES customer_profile(accountid) ON DELETE CASCADE,
    createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (blogid, customeraccountid)
);

CREATE INDEX IF NOT EXISTS idx_blog_like_customer
    ON blog_like(customeraccountid);

CREATE TABLE IF NOT EXISTS blog_comment (
    commentid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blogid INT NOT NULL
        REFERENCES blog_post(blogid) ON DELETE CASCADE,
    customeraccountid INT NOT NULL
        REFERENCES customer_profile(accountid) ON DELETE CASCADE,
    parentcommentid INT
        REFERENCES blog_comment(commentid) ON DELETE CASCADE,
    content TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Visible'
        CHECK (status IN ('Visible', 'Hidden', 'Deleted')),
    createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (BTRIM(content) <> '')
);

CREATE INDEX IF NOT EXISTS idx_blog_comment_blog_created
    ON blog_comment(blogid, createdat, commentid);
CREATE INDEX IF NOT EXISTS idx_blog_comment_customer
    ON blog_comment(customeraccountid);
CREATE INDEX IF NOT EXISTS idx_blog_comment_parent
    ON blog_comment(parentcommentid);

CREATE TABLE IF NOT EXISTS blog_share (
    shareid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blogid INT NOT NULL
        REFERENCES blog_post(blogid) ON DELETE CASCADE,
    customeraccountid INT
        REFERENCES customer_profile(accountid) ON DELETE SET NULL,
    createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE blog_share
    DROP COLUMN IF EXISTS sharechannel;

CREATE INDEX IF NOT EXISTS idx_blog_share_blog
    ON blog_share(blogid);
CREATE INDEX IF NOT EXISTS idx_blog_share_customer
    ON blog_share(customeraccountid);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'review'
          AND column_name = 'sentiment'
    ) THEN
        ALTER TABLE review
            DROP CONSTRAINT IF EXISTS ck_review_sentiment;
        ALTER TABLE review
            DROP CONSTRAINT IF EXISTS review_sentiment_check;
        DROP INDEX IF EXISTS idx_review_sentiment;
        ALTER TABLE review
            DROP COLUMN sentiment;
    END IF;

END;
$$;

ALTER TABLE review
    ADD COLUMN IF NOT EXISTS isjapanesetag BOOLEAN NOT NULL DEFAULT FALSE;

DROP TABLE IF EXISTS review_tag;
DROP TABLE IF EXISTS review_media;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'moderation_log_targettype_check'
    ) THEN
        ALTER TABLE moderation_log
            DROP CONSTRAINT moderation_log_targettype_check;
    END IF;

    ALTER TABLE moderation_log
        ADD CONSTRAINT moderation_log_targettype_check
        CHECK (targettype IN ('Review', 'BlogPost', 'BlogComment', 'Promotion', 'BadgeApplication', 'Account', 'RestaurantMedia'));
END;
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at'
    ) THEN
        DROP TRIGGER IF EXISTS trg_blog_post_updated_at ON blog_post;
        CREATE TRIGGER trg_blog_post_updated_at
        BEFORE UPDATE ON blog_post
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();

        DROP TRIGGER IF EXISTS trg_blog_comment_updated_at ON blog_comment;
        CREATE TRIGGER trg_blog_comment_updated_at
        BEFORE UPDATE ON blog_comment
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
END;
$$;

COMMIT;
