CREATE TABLE IF NOT EXISTS ADMIN_ACTION_LOG (
    LogID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AdminAccountID INT NOT NULL
        REFERENCES USER_ACCOUNT(AccountID),
    TargetAccountID INT NOT NULL
        REFERENCES USER_ACCOUNT(AccountID),
    ActionType VARCHAR(50) NOT NULL
        CHECK (ActionType IN ('UpdateUser', 'ChangeRole', 'Ban', 'Restore', 'SoftDelete')),
    ActionContent TEXT NOT NULL,
    Reason TEXT,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (BTRIM(ActionContent) <> '')
);

CREATE INDEX IF NOT EXISTS idx_admin_action_log_admin
    ON ADMIN_ACTION_LOG(AdminAccountID, CreatedAt DESC);

CREATE INDEX IF NOT EXISTS idx_admin_action_log_target
    ON ADMIN_ACTION_LOG(TargetAccountID, CreatedAt DESC);
